title: Doug Andrade
logo: /images/profile_circle.png
description: A collection of personal data science projects, as well as an outline of my education and professional experience.
show_downloads: true
theme: jekyll-theme-minimal

social:
  Linkedn: https://www.linkedin.com/in/douglasrandrade/

