title: Doug Andrade
logo: /images/profile_circle.png
description: A collection of personal analytical, machine learning projects, and professional experience
show_downloads: true
theme: jekyll-theme-minimal

social:
  Linkedn: https://www.linkedin.com/in/douglasrandrade/

